<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.im</groupId>
        <artifactId>im-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>im-friend</artifactId>
    <name>im-friend</name>
    <description>好友关系：申请、同意拒绝、列表、备注、删除、拉黑</description>

    <dependencies>
        <dependency>
            <groupId>com.im</groupId>
            <artifactId>im-common</artifactId>
        </dependency>
    </dependencies>
</project>
